### ISSUE TITLE
Add "Red Hat Authors" section?

### ISSUE THREAD

**Issue by shawndwells** [rht-labs/rht-labs-library#6]
Saw Jeremy's note on cloud-strategy and really love the idea of books at the labs!

Many Red Hatters have been published in their fields. Could we have a "Red Hat Authors" section? I think it'd be great for moral and would show customers how truly extensive their technical relationship with Red Hat can be.

**Comment by tenfourty** [comment]
Shawn, this is a great idea - do you fancy sending us a pull request to get us started?

**Comment by shawndwells** [comment]
I'm only aware of a small subset of people who wrote books, so I propose this: I'll send a link to this ticket around (and on the internal mailing list) for people to comment with their book+info here. After a weekish, I'll turn the comments into a PR.

**Comment by shawndwells** [comment]
I'll go first:

Book: [OpenStack Security Guide](http://docs.openstack.org/security-guide/)
Red Hat Authors: Shawn Wells, Keith Basil
Link to purchase a copy: Originally Hulu, looks like this was taken down. Copies can be provided by Shawn or Keith.

**Comment by shawndwells** [comment]
Book: Getting Started with OpenShift
Red Hat Authors: Steve Pousty
Purchase: [http://shop.oreilly.com/product/0636920033226.do](http://shop.oreilly.com/product/0636920033226.do)

**Comment by jduncan-rva** [comment]
I'm working on OpenShift for Operations, which should be out in the fall in print. Would happily contribute a copy.

**Comment by suehle** [comment]
Book: Raspberry Pi Hacks
Red Hat Authors: Ruth Suehle, Tom Callaway
Link to purchase a copy: http://shop.oreilly.com/product/0636920029083.do or
https://www.amazon.com/Raspberry-Pi-Hacks-Inexpensive-Computer/dp/1449362346/ref=sr_1_1?ie=UTF8&qid=1485457873&sr=8-1&keywords=raspberry+pi+hacks

**Comment by gshipley** [comment]
Book: Learning OpenShift
Red Hat Author: Grant Shipley
Link to purchase: https://www.amazon.com/Learning-OpenShift-Grant-Shipley/dp/1783980966/ref=sr_1_1?ie=UTF8&qid=1485460923&sr=8-1&keywords=learning+openshift

**Comment by gshipley** [comment]
Book: OpenShift for Developers
Red Hat Authors: Grant Shipley and Graham Dumpleton
Link to purchase: https://www.amazon.com/OpenShift-Developers-Guide-Impatient-Beginners/dp/1491961430/ref=mt_paperback?_encoding=UTF8&me=

**Comment by jhibbets** [comment]
Book: The foundation for an open source city
Red Hat Author: Jason Hibbets
Link to purchase: http://www.lulu.com/shop/jason-hibbets/the-foundation-for-an-open-source-city/paperback/product-20984645.html

**Comment by lordofthejars** [comment]
Book: Testing Java Microservices
Red Hat Authors: Alex Soto, Jason Porter
Link To purchase: https://www.manning.com/books/testing-java-microservices

**Comment by christian-posta** [comment]
Microservices for Java developers

http://www.oreilly.com/programming/free/microservices-for-java-developers.csp

**Comment by scranton** [comment]
Apache Camel Developer's Cookbook
Scott Cranton and Jakub Korab
http://a.co/80kGePZ

**Comment by shawndwells** [comment]
Added the book info of everyone above, plus tracked down the list from RHT Summit book signings. About 19 books in all!

ref: PR https://github.com/rht-labs/rht-labs-library/pull/9

**Comment by maxamillion** [comment]
I wrote a book on OpenShift but it covered Architecture v2 and I'm not sure it's worth listing anymore. If there is interest I'll post info, but the book is largely obsolete.

**Comment by shawndwells** [comment]
On 2/2/17 4:41 PM, Adam Miller wrote:
> I wrote a book on OpenShift but it covered Architecture v2 and I'm not
> sure it's worth listing anymore. If there is interest I'll post info,
> but the book is largely obsolete.

This is @tenfourty 's show, but I'd say include it. Showing RHT authors
have worked to publish over time is still a valuable message to show to
customers who visit our briefing centers.

**Comment by maxamillion** [comment]
Book: Implementing OpenShift
Red Hat Author: Adam Miller
Link to purchase: https://www.packtpub.com/virtualization-and-cloud/implementing-openshift

**Comment by tenfourty** [comment]
Yes, I'd love to see a "retired" book's section for stuff like this but that still shows off our authors. Feel free to open up a pull request to add your book to this @maxamillion.
